[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@10 && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build:prod"]

[start]
cmd = "node dist/server/node-build.mjs"
