import { useState, useCallback } from "react";
import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  ClipboardList,
  Scale,
  TreePine,
  Building2,
  Printer,
  ChevronLeft,
  FileText,
} from "lucide-react";

// ─── Types ───────────────────────────────────────────────────────────────────

type FieldType = "text" | "textarea" | "date" | "select";

interface FieldDef {
  id: string;
  label: string;
  type: FieldType;
  placeholder?: string;
  options?: string[];
  required?: boolean;
  hint?: string;
}

interface Template {
  id: string;
  title: string;
  subtitle: string;
  Icon: React.ComponentType<{ className?: string }>;
  iconBg: string;
  iconColor: string;
  law: string;
  fields: FieldDef[];
  generate: (v: Record<string, string>) => string;
}

// ─── Document generators ──────────────────────────────────────────────────────

const CSS = `
  body{font-family:'Times New Roman',Times,serif;font-size:12pt;line-height:1.9;
    margin:0;padding:2cm 2.5cm;color:#000}
  .lh{text-align:center;border-bottom:2px solid #000;padding-bottom:10px;margin-bottom:18px}
  .lh h1{font-size:13pt;margin:0 0 4px;letter-spacing:.5px}
  .lh p{font-size:10pt;margin:0;color:#333}
  .right{text-align:right}
  .subj{text-align:center;font-weight:bold;text-decoration:underline;margin:18px 0;font-size:11pt}
  ol,ul{padding-left:22px;margin:10px 0}
  li{margin:6px 0}
  .sig{margin-top:45px}
  table{width:100%;border-collapse:collapse;margin:16px 0;font-size:11pt}
  td{padding:6px 8px;border:1px solid #999}
  td:first-child{width:42%;font-weight:bold}
  .footer{border-top:1px solid #aaa;margin-top:28px;padding-top:8px;font-size:9pt;color:#555}
  @media print{body{padding:1.5cm 2cm}}
`;

function wrap(title: string, body: string) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>
<title>${title}</title><style>${CSS}</style></head><body>${body}
<div class="footer">Generated by <strong>LegalAID</strong> — Free Legal AI for Tribal &amp; Rural Communities |
National Legal Services Helpline: <strong>15100</strong> (Toll-Free, All India) |
This document is for informational purposes. Consult a qualified advocate or DLSA for legal advice.
</div></body></html>`;
}

function addr(s: string) {
  return s.replace(/\n/g, "<br/>");
}

function generateRTI(v: Record<string, string>): string {
  const name = v.applicantName || "[Your Name]";
  const body = `
<div class="lh"><h1>RIGHT TO INFORMATION APPLICATION</h1>
<p>Under Section 6(1) of the Right to Information Act, 2005</p></div>
<div class="right"><strong>${name}</strong><br/>
${addr(v.applicantAddress || "[Address]")}
${v.phone ? `<br/>Phone: ${v.phone}` : ""}</div>
<p style="margin-top:10px">Date: <strong>${v.date || "________________"}</strong></p>
<p>To,<br/>The Public Information Officer,<br/>
<strong>${v.departmentName || "[Department]"}</strong>,<br/>
${addr(v.departmentAddress || "[Dept Address]")}</p>
<div class="subj">Subject: Application for Information under the Right to Information Act, 2005</div>
<p>Respected Sir/Madam,</p>
<p>I, <strong>${name}</strong>, a citizen of India, hereby request the following information
under <strong>Section 6(1) of the Right to Information Act, 2005</strong>:</p>
<ol><li>${(v.infoSought || "[Information sought]").split("\n").join("</li><li>")}</li></ol>
<p>I request the information be provided within <strong>30 days</strong> as mandated by
Section 7(1) of the RTI Act, 2005.</p>
${v.bplCardNumber
  ? `<p>I hold <strong>BPL Card No: ${v.bplCardNumber}</strong> and am exempt from the
     application fee under the RTI (Fee &amp; Cost) Rules.</p>`
  : `<p>I enclose the application fee of <strong>₹10/-</strong> (Rupees Ten only) by way of
     ________________________ (Cash / Demand Draft / IPO / Court Fee Stamp).</p>`}
<p>If this information is not held by your department, please transfer this application to the
concerned Public Authority under <strong>Section 6(3) of the RTI Act</strong> within 5 working days.</p>
<div class="sig"><p>Yours faithfully,</p>
<p style="margin-top:42px">________________________________</p>
<p><strong>${name}</strong></p>
<p>${addr(v.applicantAddress || "[Address]")}</p>
${v.phone ? `<p>Phone: ${v.phone}</p>` : ""}</div>`;
  return wrap(`RTI Application — ${name}`, body);
}

function generateFIR(v: Record<string, string>): string {
  const name = v.applicantName || "[Your Name]";
  const body = `
<div class="lh"><h1>APPLICATION FOR REGISTRATION OF FIR</h1>
<p>Under Section 154 of the Code of Criminal Procedure, 1973</p></div>
<div class="right"><strong>${name}</strong><br/>
${addr(v.applicantAddress || "[Address]")}
${v.phone ? `<br/>Phone: ${v.phone}` : ""}</div>
<p style="margin-top:10px">Date: <strong>${v.date || "________________"}</strong></p>
<p>To,<br/>The Superintendent of Police,<br/>
<strong>${v.district || "[District]"} District</strong>,<br/>
${v.state || "Telangana"}</p>
<div class="subj">Subject: Complaint regarding refusal to register FIR by ${
  v.policeStation || "[Police Station]"
} Police Station</div>
<p>Respected Sir/Madam,</p>
<p>I, <strong>${name}</strong>, wish to bring to your notice that on <strong>${
  v.dateOfRefusal || "[date]"
}</strong>, I approached <strong>${
  v.policeStation || "[Police Station]"
} Police Station</strong> to report the following incident:</p>
<blockquote style="border-left:3px solid #666;padding-left:14px;margin:14px 0;color:#333;font-style:italic">
${addr(v.incidentDetails || "[Incident details]")}
</blockquote>
<p>The Station House Officer refused to register the FIR, which is a violation of
<strong>Section 154(1) of the Code of Criminal Procedure, 1973</strong>, which makes registration
of cognizable offences mandatory. This refusal also contravenes the directions of the
Hon'ble Supreme Court of India in <em>Lalita Kumari vs. Govt. of Uttar Pradesh</em> (2014) AIR SC 187,
which held that registration of FIR is mandatory upon receipt of information of a cognizable offence.</p>
<p>I therefore respectfully request you to:</p>
<ol>
<li>Direct <strong>${v.policeStation || "[Police Station]"} Police Station</strong> to register the FIR immediately</li>
<li>Take appropriate departmental action against the officer(s) who refused to register the FIR</li>
<li>Ensure my safety and protection during investigation</li>
</ol>
${v.witnessNames ? `<p><strong>Witnesses:</strong> ${v.witnessNames}</p>` : ""}
<div class="sig"><p>Yours faithfully,</p>
<p style="margin-top:42px">________________________________</p>
<p><strong>${name}</strong></p>
<p>${addr(v.applicantAddress || "[Address]")}</p>
${v.phone ? `<p>Phone: ${v.phone}</p>` : ""}</div>`;
  return wrap(`FIR Complaint — ${name}`, body);
}

function generateFRA(v: Record<string, string>): string {
  const name = v.applicantName || "[Your Name]";
  const estYear = v.yearsOfResidence
    ? String(2026 - parseInt(v.yearsOfResidence))
    : "____";
  const body = `
<div class="lh"><h1>CLAIM FOR RECOGNITION OF FOREST RIGHTS</h1>
<p>Under the Scheduled Tribes and Other Traditional Forest Dwellers<br/>
(Recognition of Forest Rights) Act, 2006 — Section 3</p></div>
<p>To,<br/>The Forest Rights Committee,<br/>
Gram Sabha of <strong>${v.villageName || "[Village]"}</strong>,<br/>
<strong>${v.mandal || "[Mandal]"}</strong> Mandal, <strong>${v.district || "[District]"}</strong> District</p>
<div class="right">
<strong>${name}</strong><br/>
S/o — D/o — W/o: ${v.parentName || "[Parent Name]"}<br/>
${v.villageName || "[Village]"}, ${v.mandal || "[Mandal]"}, ${v.district || "[District]"}<br/>
Date: ${v.date || "________________"}
</div>
<div class="subj">Subject: Application for Recognition of Forest Rights under the Forest Rights Act, 2006</div>
<p>Respected Members of the Forest Rights Committee,</p>
<p>I, <strong>${name}</strong>, a member of the <strong>${
  v.community || "Scheduled Tribe"
}</strong> community, have been residing in / cultivating land in
<strong>${v.villageName || "[Village]"}</strong> village for
<strong>${v.yearsOfResidence || "__"} years</strong> (since approximately ${estYear}).
I hereby apply for recognition of my forest rights under
<strong>Section 3 of the Forest Rights Act, 2006</strong>.</p>
<table>
<tr><td>Applicant Name</td><td>${name}</td></tr>
<tr><td>Community / Tribe</td><td>${v.community || "Scheduled Tribe"}</td></tr>
<tr><td>Village / Hamlet</td><td>${v.villageName || "[Village]"}, ${v.mandal || "[Mandal]"}, ${v.district || "[District]"}</td></tr>
<tr><td>Survey / Plot Numbers</td><td>${v.surveyNumbers || "[Survey Numbers]"}</td></tr>
<tr><td>Extent of Land</td><td>${v.landExtent || "[Area]"}</td></tr>
<tr><td>Nature of Use</td><td>${v.natureOfUse || "[Cultivation / Habitation]"}</td></tr>
<tr><td>Period of Occupation</td><td>${v.yearsOfResidence || "__"} years (since approximately ${estYear})</td></tr>
</table>
<p><strong>Evidence being attached:</strong></p>
<ul style="list-style:none;padding-left:0">
<li>&#9744; Photographs of cultivation / habitation</li>
<li>&#9744; Affidavits from two elderly village residents</li>
<li>&#9744; Ration card / Voter ID / Aadhaar card</li>
<li>&#9744; Revenue / patta records (if any)</li>
<li>&#9744; Bank passbook with address</li>
<li>&#9744; Any other evidence of continuous occupation</li>
</ul>
${v.additionalDetails ? `<p>${addr(v.additionalDetails)}</p>` : ""}
<p>I declare that the above information is true and correct to the best of my knowledge.</p>
<div class="sig"><p style="margin-top:42px">________________________________</p>
<p><strong>${name}</strong></p>
<p>${v.villageName || "[Village]"}, ${v.mandal || "[Mandal]"}, ${v.district || "[District]"}</p>
${v.phone ? `<p>Phone: ${v.phone}</p>` : ""}</div>`;
  return wrap(`Forest Rights Claim — ${name}`, body);
}

function generateCollector(v: Record<string, string>): string {
  const name = v.applicantName || "[Your Name]";
  const body = `
<div class="lh"><h1>GRIEVANCE APPLICATION</h1>
<p>To the District Collector — Civil Administration Grievance Redressal</p></div>
<div class="right"><strong>${name}</strong><br/>
${addr(v.applicantAddress || "[Address]")}
${v.phone ? `<br/>Phone: ${v.phone}` : ""}</div>
<p style="margin-top:10px">Date: <strong>${v.date || "________________"}</strong></p>
<p>To,<br/>The District Collector,<br/>
<strong>${v.district || "[District]"} District</strong>,<br/>
[State]</p>
<div class="subj">Subject: ${v.subject || "[Subject of Complaint]"}</div>
<p>Respected Sir/Madam,</p>
<p>I, <strong>${name}</strong>, a resident of the address mentioned above, submit this
grievance regarding: <strong>${v.issueType || "[Issue Type]"}</strong>.</p>
<p><strong>Details of the Issue:</strong></p>
<p style="border-left:3px solid #666;padding-left:14px;margin:14px 0;color:#333">
${addr(v.issueDetails || "[Issue details]")}
</p>
${v.previousComplaints
  ? `<p><strong>Previous Complaints Filed:</strong> ${v.previousComplaints}</p>`
  : ""}
<p><strong>Relief / Action Sought:</strong></p>
<p style="border-left:3px solid #666;padding-left:14px;margin:14px 0;color:#333">
${addr(v.reliefSought || "[Relief sought]")}
</p>
<p>I request you to kindly look into this matter and take appropriate action at the earliest.
I am available for any further information or inquiry.</p>
<div class="sig"><p>Yours faithfully,</p>
<p style="margin-top:42px">________________________________</p>
<p><strong>${name}</strong></p>
<p>${addr(v.applicantAddress || "[Address]")}</p>
${v.phone ? `<p>Phone: ${v.phone}</p>` : ""}</div>`;
  return wrap(`Collector Complaint — ${name}`, body);
}

// ─── Template definitions ────────────────────────────────────────────────────

const TEMPLATES: Template[] = [
  {
    id: "rti",
    title: "RTI Application",
    subtitle: "Request information from any government department",
    Icon: ClipboardList,
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
    law: "Right to Information Act, 2005 — Section 6",
    generate: generateRTI,
    fields: [
      { id: "applicantName", label: "Your Full Name", type: "text", placeholder: "e.g. Ramu Naik", required: true },
      { id: "applicantAddress", label: "Your Address", type: "textarea", placeholder: "Village, Mandal, District, State — PIN", required: true },
      { id: "phone", label: "Phone Number", type: "text", placeholder: "10-digit mobile number" },
      { id: "departmentName", label: "Department / Office Name", type: "text", placeholder: "e.g. District Collector Office, Adilabad", required: true },
      { id: "departmentAddress", label: "Department Address", type: "textarea", placeholder: "Full postal address of the office", required: true },
      { id: "infoSought", label: "Information Sought", type: "textarea", placeholder: "Describe exactly what you want — e.g. 'Copies of all documents related to land survey No. 123 in Vanthala village, including the latest patta records and mutation entries'", required: true, hint: "Be as specific as possible. Each item can go on a new line." },
      { id: "bplCardNumber", label: "BPL Card Number (optional — fee waived for BPL holders)", type: "text", placeholder: "Leave blank if you do not have a BPL card" },
      { id: "date", label: "Date", type: "date", required: true },
    ],
  },
  {
    id: "fir",
    title: "FIR Complaint to SP",
    subtitle: "When police refuse to register your First Information Report",
    Icon: Scale,
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
    law: "Code of Criminal Procedure, 1973 — Section 154",
    generate: generateFIR,
    fields: [
      { id: "applicantName", label: "Your Full Name", type: "text", placeholder: "e.g. Lakshmi Bai", required: true },
      { id: "applicantAddress", label: "Your Address", type: "textarea", placeholder: "Village, Mandal, District, State — PIN", required: true },
      { id: "phone", label: "Phone Number", type: "text", placeholder: "10-digit mobile number" },
      { id: "district", label: "District", type: "text", placeholder: "e.g. Adilabad", required: true },
      { id: "state", label: "State", type: "select", options: ["Telangana", "Andhra Pradesh", "Other"], required: true },
      { id: "policeStation", label: "Police Station Name", type: "text", placeholder: "e.g. Utnoor Police Station", required: true },
      { id: "dateOfRefusal", label: "Date Police Refused to Register FIR", type: "date", required: true },
      { id: "incidentDetails", label: "Incident Details", type: "textarea", placeholder: "Describe what happened — when, where, who did what, and the nature of the offence", required: true },
      { id: "witnessNames", label: "Witness Names (if any)", type: "text", placeholder: "e.g. Ramu s/o Narsaiah, Kamla w/o Ramaiah" },
      { id: "date", label: "Date of This Letter", type: "date", required: true },
    ],
  },
  {
    id: "fra",
    title: "Forest Rights Claim",
    subtitle: "Apply for recognition of your forest land rights",
    Icon: TreePine,
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
    law: "Forest Rights Act, 2006 — Section 3",
    generate: generateFRA,
    fields: [
      { id: "applicantName", label: "Your Full Name", type: "text", placeholder: "e.g. Soma Naik", required: true },
      { id: "parentName", label: "Father's / Husband's Name", type: "text", placeholder: "e.g. Bhima Naik", required: true },
      { id: "community", label: "Tribe / Community", type: "text", placeholder: "e.g. Gond, Koya, Lambada, Banjara", required: true },
      { id: "villageName", label: "Village Name", type: "text", placeholder: "e.g. Vanthala", required: true },
      { id: "mandal", label: "Mandal", type: "text", placeholder: "e.g. Utnoor", required: true },
      { id: "district", label: "District", type: "text", placeholder: "e.g. Adilabad", required: true },
      { id: "surveyNumbers", label: "Survey / Plot Numbers", type: "text", placeholder: "e.g. S.No. 123/A, 124", required: true },
      { id: "landExtent", label: "Extent of Land", type: "text", placeholder: "e.g. 2.50 acres", required: true },
      { id: "natureOfUse", label: "Nature of Use", type: "select", options: ["Cultivation", "Habitation (Home)", "Both Cultivation & Habitation", "Non-Timber Forest Produce Collection"], required: true },
      { id: "yearsOfResidence", label: "Years Living / Farming on This Land", type: "text", placeholder: "e.g. 25", required: true },
      { id: "additionalDetails", label: "Additional Details (optional)", type: "textarea", placeholder: "Any other relevant information about your claim" },
      { id: "phone", label: "Phone Number", type: "text", placeholder: "10-digit mobile number" },
      { id: "date", label: "Date", type: "date", required: true },
    ],
  },
  {
    id: "collector",
    title: "Complaint to Collector",
    subtitle: "Official grievance to the District Collector for any issue",
    Icon: Building2,
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
    law: "Civil Administration — District Grievance Redressal",
    generate: generateCollector,
    fields: [
      { id: "applicantName", label: "Your Full Name", type: "text", placeholder: "e.g. Ramu Naik", required: true },
      { id: "applicantAddress", label: "Your Address", type: "textarea", placeholder: "Village, Mandal, District, State — PIN", required: true },
      { id: "phone", label: "Phone Number", type: "text", placeholder: "10-digit mobile number" },
      { id: "district", label: "District", type: "text", placeholder: "e.g. Adilabad", required: true },
      { id: "subject", label: "Subject of Complaint (one line)", type: "text", placeholder: "e.g. Non-issuance of caste certificate despite repeated applications", required: true },
      { id: "issueType", label: "Category of Issue", type: "select", options: ["Land / Patta Records", "Caste Certificate", "Forest Rights", "MGNREGA Wages", "SC/ST Atrocity", "Encroachment by Officials", "Revenue Records", "Other Government Scheme"], required: true },
      { id: "issueDetails", label: "Details of the Issue", type: "textarea", placeholder: "Describe what happened, who is responsible, and what action has been taken so far", required: true },
      { id: "previousComplaints", label: "Previous Complaints Filed (if any)", type: "text", placeholder: "e.g. Complaint at MRO office on 15-Jan-2026, no response received" },
      { id: "reliefSought", label: "Relief / Action Sought", type: "textarea", placeholder: "What exactly do you want the Collector to do? Be specific.", required: true },
      { id: "date", label: "Date", type: "date", required: true },
    ],
  },
];

// ─── Component ────────────────────────────────────────────────────────────────

export default function DocumentTemplates() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});

  const template = TEMPLATES.find((t) => t.id === selectedId) ?? null;

  const handleSelect = useCallback((id: string) => {
    setSelectedId(id);
    setValues({});
  }, []);

  const handleChange = useCallback((id: string, val: string) => {
    setValues((prev) => ({ ...prev, [id]: val }));
  }, []);

  const handlePrint = useCallback(() => {
    if (!template) return;
    const html = template.generate(values);
    const win = window.open("", "_blank");
    if (!win) {
      alert("Please allow pop-ups to print the document.");
      return;
    }
    win.document.write(html);
    win.document.close();
    // Give the browser a moment to render before triggering print
    setTimeout(() => win.print(), 400);
  }, [template, values]);

  const filledCount = template
    ? template.fields.filter((f) => f.required && values[f.id]?.trim()).length
    : 0;
  const requiredCount = template ? template.fields.filter((f) => f.required).length : 0;
  const isReady = filledCount === requiredCount;

  return (
    <Layout>
      <div className="mx-auto max-w-4xl space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <FileText className="w-6 h-6 text-blue-600" />
            Legal Document Templates
          </h1>
          <p className="text-slate-500 text-sm mt-1">
            Fill in your details, preview the document, and print or save as PDF — free, no sign-up needed.
          </p>
        </div>

        {/* Template selector */}
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {TEMPLATES.map((t) => (
            <button
              key={t.id}
              onClick={() => handleSelect(t.id)}
              className={`rounded-xl border p-4 text-left transition-all hover:shadow-md ${
                selectedId === t.id
                  ? "border-blue-500 bg-blue-50 shadow-md ring-2 ring-blue-200"
                  : "border-slate-200 bg-white hover:border-slate-300"
              }`}
            >
              <div className={`inline-flex rounded-lg p-2 mb-2 ${t.iconBg}`}>
                <t.Icon className={`w-5 h-5 ${t.iconColor}`} />
              </div>
              <div className="font-semibold text-slate-900 text-sm">{t.title}</div>
              <div className="text-xs text-slate-500 mt-0.5">{t.subtitle}</div>
            </button>
          ))}
        </div>

        {/* Form + Live preview side by side */}
        {template && (
          <div className="grid gap-6 lg:grid-cols-2">
            {/* Form */}
            <div className="rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 p-5 space-y-4">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setSelectedId(null)}
                  className="text-slate-400 hover:text-slate-700 transition-colors"
                  title="Back to templates"
                >
                  <ChevronLeft className="w-5 h-5" />
                </button>
                <div>
                  <h2 className="font-bold text-slate-900">{template.title}</h2>
                  <p className="text-xs text-slate-500">{template.law}</p>
                </div>
              </div>

              <div className="space-y-3">
                {template.fields.map((field) => (
                  <div key={field.id} className="space-y-1">
                    <label className="text-sm font-medium text-slate-700">
                      {field.label}
                      {field.required && <span className="text-red-500 ml-0.5">*</span>}
                    </label>
                    {field.type === "textarea" ? (
                      <textarea
                        rows={3}
                        value={values[field.id] ?? ""}
                        onChange={(e) => handleChange(field.id, e.target.value)}
                        placeholder={field.placeholder}
                        className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 resize-y"
                      />
                    ) : field.type === "select" ? (
                      <select
                        value={values[field.id] ?? ""}
                        onChange={(e) => handleChange(field.id, e.target.value)}
                        className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
                      >
                        <option value="">— Select —</option>
                        {field.options?.map((o) => <option key={o}>{o}</option>)}
                      </select>
                    ) : (
                      <Input
                        type={field.type}
                        value={values[field.id] ?? ""}
                        onChange={(e) => handleChange(field.id, e.target.value)}
                        placeholder={field.placeholder}
                        className="bg-slate-50"
                      />
                    )}
                    {field.hint && (
                      <p className="text-xs text-slate-400">{field.hint}</p>
                    )}
                  </div>
                ))}
              </div>

              {/* Progress + Print */}
              <div className="pt-2 space-y-3">
                <div className="flex items-center gap-2 text-xs text-slate-500">
                  <div className="flex-1 rounded-full bg-slate-100 h-1.5">
                    <div
                      className="rounded-full bg-blue-500 h-1.5 transition-all"
                      style={{ width: `${requiredCount ? (filledCount / requiredCount) * 100 : 0}%` }}
                    />
                  </div>
                  <span>{filledCount}/{requiredCount} required fields</span>
                </div>
                <Button
                  onClick={handlePrint}
                  disabled={!isReady}
                  className="w-full bg-blue-600 hover:bg-blue-700 gap-2"
                >
                  <Printer className="w-4 h-4" />
                  {isReady ? "Print / Save as PDF" : "Fill required fields to print"}
                </Button>
                <p className="text-xs text-center text-slate-400">
                  In the print dialog, choose "Save as PDF" to get a file.
                </p>
              </div>
            </div>

            {/* Live preview */}
            <div className="rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 overflow-hidden flex flex-col">
              <div className="bg-slate-100 px-4 py-2 flex items-center gap-2 border-b border-slate-200">
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400" />
                  <div className="w-3 h-3 rounded-full bg-yellow-400" />
                  <div className="w-3 h-3 rounded-full bg-green-400" />
                </div>
                <span className="text-xs text-slate-500 font-medium">Document Preview</span>
              </div>
              <div className="flex-1 overflow-y-auto p-5 font-serif text-[11px] leading-relaxed text-slate-800 space-y-2">
                <DocumentPreview template={template} values={values} />
              </div>
            </div>
          </div>
        )}

        {/* Bottom tip */}
        {!template && (
          <div className="rounded-xl bg-blue-50 border border-blue-100 p-4 text-sm text-blue-800">
            <strong>How it works:</strong> Select a template above → fill in your details →
            preview updates live → click "Print / Save as PDF" to get your document.
            All documents are formatted as proper legal letters citing the relevant Indian law.
          </div>
        )}
      </div>
    </Layout>
  );
}

// ─── Inline preview component ─────────────────────────────────────────────────

function DocumentPreview({
  template,
  values,
}: {
  template: Template;
  values: Record<string, string>;
}) {
  const v = values;
  const name = v.applicantName || "[Your Name]";
  const addr = (s: string) => s ? s.split("\n").map((l, i) => <span key={i}>{l}<br /></span>) : "[Address]";

  if (template.id === "rti") {
    return (
      <>
        <div className="text-center border-b-2 border-black pb-2 mb-3">
          <div className="font-bold uppercase tracking-wide">Right to Information Application</div>
          <div className="text-slate-500">Section 6(1), Right to Information Act, 2005</div>
        </div>
        <div className="text-right space-y-0.5">
          <div className="font-bold">{name}</div>
          <div className="text-slate-600">{addr(v.applicantAddress || "")}</div>
          {v.phone && <div>Phone: {v.phone}</div>}
          <div className="mt-1">Date: {v.date || "________________"}</div>
        </div>
        <div className="mt-2">
          To,<br />The Public Information Officer,<br />
          <strong>{v.departmentName || "[Department]"}</strong>,<br />
          <span className="text-slate-600">{addr(v.departmentAddress || "")}</span>
        </div>
        <div className="text-center font-bold underline my-2">
          Subject: Application for Information under the Right to Information Act, 2005
        </div>
        <p>Respected Sir/Madam,</p>
        <p>I, <strong>{name}</strong>, a citizen of India, hereby request the following information under <strong>Section 6(1) of the RTI Act, 2005</strong>:</p>
        {v.infoSought && (
          <ol className="list-decimal pl-4 space-y-1">
            {v.infoSought.split("\n").map((line, i) => <li key={i}>{line}</li>)}
          </ol>
        )}
        <p className="mt-2">I request the information within <strong>30 days</strong> as per Section 7(1).</p>
        <div className="mt-4">Yours faithfully,<br /><br /><br />
          <strong>{name}</strong><br />
          <span className="text-slate-600">{addr(v.applicantAddress || "")}</span>
        </div>
      </>
    );
  }

  if (template.id === "fir") {
    return (
      <>
        <div className="text-center border-b-2 border-black pb-2 mb-3">
          <div className="font-bold uppercase tracking-wide">Application for Registration of FIR</div>
          <div className="text-slate-500">Section 154, Code of Criminal Procedure, 1973</div>
        </div>
        <div className="text-right space-y-0.5">
          <div className="font-bold">{name}</div>
          <div className="text-slate-600">{addr(v.applicantAddress || "")}</div>
          <div className="mt-1">Date: {v.date || "________________"}</div>
        </div>
        <div className="mt-2">
          To,<br />The Superintendent of Police,<br />
          <strong>{v.district || "[District]"} District</strong>, {v.state || "Telangana"}
        </div>
        <div className="text-center font-bold underline my-2">
          Subject: Complaint regarding refusal to register FIR by {v.policeStation || "[Police Station]"}
        </div>
        <p>I, <strong>{name}</strong>, report that on <strong>{v.dateOfRefusal || "[date]"}</strong>, I approached <strong>{v.policeStation || "[Station]"}</strong> but the FIR was refused — violating <strong>Section 154(1) CrPC</strong> and the Supreme Court's direction in <em>Lalita Kumari (2014)</em>.</p>
        {v.incidentDetails && <p className="border-l-2 border-slate-400 pl-2 italic text-slate-700">{v.incidentDetails}</p>}
        <p className="mt-2">I request immediate FIR registration and action against the refusing officer.</p>
        <div className="mt-4">Yours faithfully,<br /><br /><br />
          <strong>{name}</strong>
        </div>
      </>
    );
  }

  if (template.id === "fra") {
    const estYear = v.yearsOfResidence ? String(2026 - parseInt(v.yearsOfResidence)) : "____";
    return (
      <>
        <div className="text-center border-b-2 border-black pb-2 mb-3">
          <div className="font-bold uppercase tracking-wide">Claim for Recognition of Forest Rights</div>
          <div className="text-slate-500">Forest Rights Act, 2006 — Section 3</div>
        </div>
        <div className="mt-2">
          To,<br />The Forest Rights Committee,<br />
          Gram Sabha of <strong>{v.villageName || "[Village]"}</strong>,<br />
          {v.mandal || "[Mandal]"} Mandal, {v.district || "[District]"} District
        </div>
        <div className="text-center font-bold underline my-2">
          Subject: Application for Recognition of Forest Rights under FRA 2006
        </div>
        <p>I, <strong>{name}</strong>, a <strong>{v.community || "Scheduled Tribe"}</strong> member, have been residing/cultivating in <strong>{v.villageName || "[Village]"}</strong> for <strong>{v.yearsOfResidence || "__"} years</strong> (since ~{estYear}). I apply under <strong>Section 3 of the Forest Rights Act, 2006</strong>.</p>
        <table className="w-full text-[10px] border-collapse mt-2">
          <tbody>
            {[
              ["Survey Numbers", v.surveyNumbers],
              ["Extent", v.landExtent],
              ["Nature of Use", v.natureOfUse],
              ["Years Occupied", v.yearsOfResidence],
            ].map(([k, val]) => (
              <tr key={k} className="border border-slate-300">
                <td className="p-1 font-bold border-r border-slate-300 w-2/5">{k}</td>
                <td className="p-1">{val || "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="mt-4">I declare the above information is true.<br /><br /><br />
          <strong>{name}</strong><br />
          {v.villageName || "[Village]"}, {v.mandal || "[Mandal]"}, {v.district || "[District]"}
        </div>
      </>
    );
  }

  // Collector
  return (
    <>
      <div className="text-center border-b-2 border-black pb-2 mb-3">
        <div className="font-bold uppercase tracking-wide">Grievance Application</div>
        <div className="text-slate-500">To the District Collector</div>
      </div>
      <div className="text-right space-y-0.5">
        <div className="font-bold">{name}</div>
        <div className="text-slate-600">{addr(v.applicantAddress || "")}</div>
        <div className="mt-1">Date: {v.date || "________________"}</div>
      </div>
      <div className="mt-2">
        To,<br />The District Collector,<br />
        <strong>{v.district || "[District]"} District</strong>
      </div>
      <div className="text-center font-bold underline my-2">
        Subject: {v.subject || "[Subject of Complaint]"}
      </div>
      <p>I, <strong>{name}</strong>, submit this grievance regarding: <strong>{v.issueType || "[Issue Type]"}</strong>.</p>
      {v.issueDetails && <p className="border-l-2 border-slate-400 pl-2 italic text-slate-700">{v.issueDetails}</p>}
      {v.reliefSought && <><p className="font-bold mt-2">Relief Sought:</p><p>{v.reliefSought}</p></>}
      <div className="mt-4">Yours faithfully,<br /><br /><br />
        <strong>{name}</strong>
      </div>
    </>
  );
}
